import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    // Generated by openapi-typescript (Nx target admin:api-types); never hand-edited.
    ignores: ['**/dist', '**/out-tsc', 'apps/admin/src/app/core/api/api-schema.ts'],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            {
              sourceTag: '*',
              onlyDependOnLibsWithTags: ['*'],
            },
            {
              // libs/chat 是 admin 與官網訪客對話視窗（apps/widget）共用的對話元件：
              // 不可依賴 admin 或其他 lib（Angular Material 的 theme-pack 與 ui 也不行）。
              sourceTag: 'scope:chat',
              onlyDependOnLibsWithTags: ['scope:chat'],
            },
            {
              // apps/widget（嵌在客戶網站的訪客視窗）只能用 libs/chat：不帶 Material、theme-pack、ui。
              sourceTag: 'scope:widget',
              onlyDependOnLibsWithTags: ['scope:chat'],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {},
  },
];
