using System.Text.Json.Serialization;
using SmartAgri.Domain.Organizations;

namespace SmartAgri.Domain.Databases;

/// <summary>Where a submission was made. Wire names equal the frontend's
/// <c>DatabaseRecordSource</c> (<c>database.model.ts</c>).</summary>
[JsonConverter(typeof(JsonStringEnumConverter<DatabaseSubmissionSource>))]
public enum DatabaseSubmissionSource
{
    /// <summary>The standalone form (表單連結, M4 #145).</summary>
    [JsonStringEnumMemberName("form-link")]
    FormLink,

    /// <summary>A form an assistant requested in a conversation (M4 #148).</summary>
    [JsonStringEnumMemberName("assistant-conversation")]
    AssistantConversation,
}

/// <summary>
/// What the member was shown and agreed to before submitting (送出前的同意內容), frozen at the
/// moment of submission: the receipt shows exactly this even after the database is renamed, its
/// purpose rewritten or its data managers changed. None of it is what the member filled in.
/// </summary>
/// <param name="DatabaseName">The database's name at submission.</param>
/// <param name="Purpose">The collection purpose at submission.</param>
/// <param name="Recipient">The receiving unit, e.g. <c>安心商行（客戶資料庫）</c>.</param>
/// <param name="Viewers">Who could actually read the record at submission (designated data
/// managers holding <c>read-consented-submissions</c>), by display name.</param>
/// <param name="SensitiveNotice">The sensitive-data warning shown with the form.</param>
public sealed record DatabaseConsentTerms(
    string DatabaseName,
    string Purpose,
    string Recipient,
    IReadOnlyList<string> Viewers,
    string SensitiveNotice);

/// <summary>
/// The <b>trail</b> (軌跡) of one consented submission to a database (M4 #145): who submitted
/// to which database through which form version and channel, when, under which consent terms,
/// and its receipt number. It holds <b>nothing the member filled in</b>: the answers and the
/// field snapshot live in <see cref="DatabaseSubmissionEntry"/> rows, so withdrawal (#146) can
/// delete every entry and set <see cref="WithdrawnAt"/>, leaving exactly the "submitted, then
/// withdrawn" trail the withdrawal ADR asks for (<c>docs/adr/2026-09-25-withdrawal-and-retention.md</c>).
/// </summary>
/// <remarks>
/// <para>
/// A row only exists for a submission the member explicitly consented to and the server
/// validated: there is no "draft" or "not consented" state, so a refused or cancelled form leaves
/// no structured record at all. The row and its entries are written in one save.
/// </para>
/// <para>
/// <see cref="IdempotencyKey"/> is generated by the client once per form fill and reused for every
/// retry; the database refuses a second row with the same key from the same submitter (unique
/// index), which is what makes a retried or doubly sent submission produce one record.
/// </para>
/// </remarks>
public sealed class DatabaseSubmission : IOrganizationScoped
{
    public const int ReceiptNumberMaxLength = 32;

    /// <summary>For EF Core materialization.</summary>
    private DatabaseSubmission()
    {
    }

    public Guid Id { get; private set; }

    public Guid OrganizationId { get; private set; }

    public Guid DatabaseId { get; private set; }

    /// <summary>The exact form version the member filled in and saw (composite foreign key to
    /// <c>DatabaseFormVersions (Id, OrganizationId)</c>).</summary>
    public Guid FormVersionId { get; private set; }

    /// <summary>Copied from the version for display and for the stale-form check of a retry.</summary>
    public int FormVersionNumber { get; private set; }

    /// <summary>The member who submitted (an account of the same organization).</summary>
    public Guid SubmittedByAccountId { get; private set; }

    /// <summary>The client's key for this form fill, unique per submitter.</summary>
    public Guid IdempotencyKey { get; private set; }

    public DatabaseSubmissionSource Source { get; private set; }

    /// <summary>Shown on the receipt, e.g. <c>R-20261003-1A2B3C4D5E</c>; derived from
    /// <see cref="Id"/>, unique per organization.</summary>
    public string ReceiptNumber { get; private set; } = string.Empty;

    /// <summary>When the server accepted it (also the moment of consent).</summary>
    public DateTimeOffset SubmittedAt { get; private set; }

    public DatabaseConsentTerms ConsentTerms { get; private set; } = null!;

    /// <summary>Set by withdrawal (#146), together with deleting the entries; always
    /// <see langword="null"/> in #145.</summary>
    public DateTimeOffset? WithdrawnAt { get; private set; }

    public static DatabaseSubmission Create(
        Database database,
        DatabaseFormVersion formVersion,
        Guid submittedByAccountId,
        Guid idempotencyKey,
        DatabaseSubmissionSource source,
        DatabaseConsentTerms consentTerms,
        DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(database);
        ArgumentNullException.ThrowIfNull(formVersion);
        ArgumentNullException.ThrowIfNull(consentTerms);
        if (formVersion.DatabaseId != database.Id || formVersion.OrganizationId != database.OrganizationId)
        {
            throw new ArgumentException("The form version must belong to the database.", nameof(formVersion));
        }

        if (submittedByAccountId == Guid.Empty)
        {
            throw new ArgumentException("An id must not be empty.", nameof(submittedByAccountId));
        }

        if (idempotencyKey == Guid.Empty)
        {
            throw new ArgumentException("An idempotency key must not be empty.", nameof(idempotencyKey));
        }

        if (!Enum.IsDefined(source))
        {
            throw new ArgumentOutOfRangeException(nameof(source), source, "Not a declared source.");
        }

        var id = Guid.CreateVersion7(now);
        return new DatabaseSubmission
        {
            Id = id,
            OrganizationId = database.OrganizationId,
            DatabaseId = database.Id,
            FormVersionId = formVersion.Id,
            FormVersionNumber = formVersion.VersionNumber,
            SubmittedByAccountId = submittedByAccountId,
            IdempotencyKey = idempotencyKey,
            Source = source,
            ReceiptNumber = ReceiptNumberFor(id, now),
            SubmittedAt = now,
            ConsentTerms = consentTerms with { Viewers = [.. consentTerms.Viewers] },
        };
    }

    /// <summary><c>R-</c>, the UTC date, then the last ten hex digits of the id (its random
    /// part), upper case.</summary>
    public static string ReceiptNumberFor(Guid id, DateTimeOffset at)
    {
        var hex = id.ToString("N");
        return $"R-{at.UtcDateTime:yyyyMMdd}-{hex[^10..].ToUpperInvariant()}";
    }
}

/// <summary>
/// One field of a submission: the <b>content</b> (填寫內容). Holds the snapshot of the field as it
/// was at submission (label, type, unit, the displayed answer) and the typed value — text for
/// text, date and single choice, a number for number and scale, the chosen options (in the form's
/// order) for multiple choice; all empty when an optional field was left blank. Later form
/// versions never change these rows, so a receipt reads the same forever. Withdrawal (#146)
/// deletes them.
/// </summary>
public sealed class DatabaseSubmissionEntry : IOrganizationScoped
{
    /// <summary>For EF Core materialization.</summary>
    private DatabaseSubmissionEntry()
    {
    }

    public Guid SubmissionId { get; private set; }

    public Guid OrganizationId { get; private set; }

    /// <summary>The field's position in the form version (0-based).</summary>
    public int Position { get; private set; }

    /// <summary>The field's stable id across versions (<c>field-…</c>), for #147's comparisons.</summary>
    public string FieldId { get; private set; } = string.Empty;

    public string Label { get; private set; } = string.Empty;

    public DatabaseFieldType FieldType { get; private set; }

    /// <summary>A number field's unit; empty otherwise.</summary>
    public string Unit { get; private set; } = string.Empty;

    /// <summary>The answer as shown on the receipt (<c>未填寫</c> when blank).</summary>
    public string Display { get; private set; } = string.Empty;

    public string? TextValue { get; private set; }

    public double? NumberValue { get; private set; }

    public string[] ChoiceValues { get; private set; } = [];

    public static DatabaseSubmissionEntry Create(
        DatabaseSubmission submission,
        int position,
        DatabaseFormField field,
        string display,
        string? text,
        double? number,
        IReadOnlyList<string> choices)
    {
        ArgumentNullException.ThrowIfNull(submission);
        ArgumentNullException.ThrowIfNull(field);
        ArgumentNullException.ThrowIfNull(display);
        ArgumentNullException.ThrowIfNull(choices);
        ArgumentOutOfRangeException.ThrowIfNegative(position);

        return new DatabaseSubmissionEntry
        {
            SubmissionId = submission.Id,
            OrganizationId = submission.OrganizationId,
            Position = position,
            FieldId = field.Id,
            Label = field.Label,
            FieldType = field.Type,
            Unit = field.Unit,
            Display = display,
            TextValue = text,
            NumberValue = number,
            ChoiceValues = [.. choices],
        };
    }
}
