using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SmartAgri.Api.Authentication;
using SmartAgri.Api.Authorization;
using SmartAgri.Api.Errors;
using SmartAgri.Application.Databases;
using SmartAgri.Domain.Accounts;
using SmartAgri.Domain.Databases;
using SmartAgri.Infrastructure;

namespace SmartAgri.Api.Databases;

/// <summary>
/// <c>GET /api/v1/databases/{id}/submission-form</c>: everything a member is shown before
/// consenting (提交資訊). <see cref="Viewers"/> are the accounts that can actually read the
/// record now (designated data managers holding <c>read-consented-submissions</c>), by name.
/// </summary>
/// <param name="Recipient">The receiving unit, <c>組織名稱（資料庫名稱）</c>.</param>
/// <param name="Form">The current form; its <c>versionNumber</c> goes back with the submission.</param>
public sealed record DatabaseSubmissionFormView(
    Guid DatabaseId,
    string DatabaseName,
    string Purpose,
    string Recipient,
    IReadOnlyList<string> Viewers,
    string SensitiveNotice,
    string WithdrawalNotice,
    DatabaseFormView Form);

/// <summary>
/// <c>POST /api/v1/databases/{id}/submission-form/review</c> request: the answers to check before
/// the member is asked to consent, and the form version they were filled in.
/// </summary>
public sealed record ReviewDatabaseSubmissionRequest(int? FormVersionNumber, IReadOnlyDictionary<string, JsonElement>? Answers);

/// <summary>One field of a receipt or a record, as it was at submission.</summary>
public sealed record DatabaseSubmissionEntryView(string FieldId, string Label, DatabaseFieldType Type, string Display);

/// <summary>
/// A submission receipt (回執): returned by a successful submission (and by every retry of it) and
/// by <c>GET /api/v1/submissions/{id}</c> to its submitter. Everything here is the snapshot taken
/// at submission — later form versions, renames or data-manager changes do not change it.
/// </summary>
/// <param name="Id">The submission's id (for <c>GET /api/v1/submissions/{id}</c>).</param>
/// <param name="ReceiptNumber">Shown to the member, e.g. <c>R-20261003-1A2B3C4D5E</c>.</param>
/// <param name="Viewers">Who could read the record at submission.</param>
/// <param name="FormVersionId">The form version filled in.</param>
public sealed record DatabaseSubmissionReceiptView(
    Guid Id,
    string ReceiptNumber,
    DateTimeOffset SubmittedAt,
    Guid DatabaseId,
    string DatabaseName,
    string Purpose,
    string Recipient,
    IReadOnlyList<string> Viewers,
    Guid FormVersionId,
    int FormVersionNumber,
    DatabaseSubmissionSource Source,
    IReadOnlyList<DatabaseSubmissionEntryView> Entries);

/// <summary>One consented record as a data manager reads it.</summary>
public sealed record DatabaseSubmittedRecordView(
    Guid Id,
    string ReceiptNumber,
    DateTimeOffset SubmittedAt,
    DatabaseSubmissionSource Source,
    DatabaseAccountView Submitter,
    int FormVersionNumber,
    IReadOnlyList<DatabaseSubmissionEntryView> Entries);

/// <summary><c>GET /api/v1/databases/{id}/records</c>: the consented records, newest first.</summary>
public sealed record DatabaseRecordListView(Guid DatabaseId, IReadOnlyList<DatabaseSubmittedRecordView> Records);

/// <summary>
/// <c>POST /api/v1/databases/{id}/submissions</c> request. Every member is lenient so a missing one
/// is this endpoint's own <c>422</c>, not a binding failure.
/// </summary>
/// <param name="SubmissionId">Generated by the client once per form fill and sent again on every
/// retry (the idempotency key).</param>
/// <param name="FormVersionNumber">The form version the member filled in.</param>
/// <param name="Consent">Must be <see langword="true"/>.</param>
/// <param name="Answers">By field id: a string, or an array of strings for multiple choice.</param>
public sealed record SubmitDatabaseEntryRequest(
    Guid? SubmissionId,
    int? FormVersionNumber,
    bool? Consent,
    IReadOnlyDictionary<string, JsonElement>? Answers);

/// <summary>
/// The standalone form (表單連結) of a database and its receipts (M4 #145): a member with
/// <c>submit-authorized-forms</c> reads what will happen to their answers, consents explicitly and
/// submits; the server validates everything again (<see cref="DatabaseSubmissionService"/>) and
/// returns a receipt. Designated data managers holding <c>read-consented-submissions</c> read the
/// records (<see cref="DatabaseRecordReaders"/>, re-evaluated on every request).
/// </summary>
/// <remarks>
/// <para>
/// Status codes: <c>201</c> new receipt (<c>Location</c> = the receipt); <c>200</c> the same receipt
/// for a retry with the same <c>submissionId</c> and content (nothing written); <c>403
/// authorized-form</c> byte-identical for a missing database, another organization's and a caller
/// without the permission; <c>409 form-version-changed</c> when the form changed after it was
/// loaded; <c>409 submission-key-reused</c> when the <c>submissionId</c> was already used for other
/// content (a conflict with existing state, not a malformed request, hence 409 rather than 422);
/// <c>422</c> for a missing key or version, invalid answers (<c>answers.&lt;field id&gt;</c>), or no
/// consent (<c>reason: consent-required</c>, key <c>consent</c>). Nothing is written on any refusal.
/// </para>
/// <para>
/// An assistant's in-conversation form request (#148) is another entry point to the same
/// <see cref="DatabaseSubmissionService"/>, with its own authorization and
/// <see cref="DatabaseSubmissionSource.AssistantConversation"/>.
/// </para>
/// </remarks>
public static class DatabaseSubmissionEndpoints
{
    public const string SubmissionsPath = "/api/v1/submissions";

    public const string FormChangedMessage = "這份表單已更新，請重新載入最新的表單後再填寫。你這次填寫的內容尚未送出。";

    public const string KeyReusedReason = "submission-key-reused";

    public const string KeyReusedMessage = "這個提交編號已經用在另一份內容上，資料沒有送出。請重新載入表單後再填寫。";

    public const string ConsentRequiredReason = "consent-required";

    public static IEndpointRouteBuilder MapDatabaseSubmissionEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var databases = endpoints.MapGroup(DatabaseEndpoints.DatabasesPath).RequireAuthorization();

        databases.MapGet("/{id:guid}/submission-form", GetFormAsync)
            .RequirePermission(AccountPermission.SubmitAuthorizedForms, ForbiddenReason.AuthorizedForm)
            .Produces<DatabaseSubmissionFormView>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status401Unauthorized)
            .Produces(StatusCodes.Status403Forbidden);

        databases.MapPost("/{id:guid}/submission-form/review", ReviewAsync)
            .RequirePermission(AccountPermission.SubmitAuthorizedForms, ForbiddenReason.AuthorizedForm)
            .Produces<DatabaseTrialPreviewView>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status401Unauthorized)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status409Conflict)
            .Produces(StatusCodes.Status422UnprocessableEntity);

        databases.MapPost("/{id:guid}/submissions", SubmitAsync)
            .RequirePermission(AccountPermission.SubmitAuthorizedForms, ForbiddenReason.AuthorizedForm)
            .Produces<DatabaseSubmissionReceiptView>(StatusCodes.Status201Created)
            .Produces<DatabaseSubmissionReceiptView>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status401Unauthorized)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status409Conflict)
            .Produces(StatusCodes.Status422UnprocessableEntity);

        databases.MapGet("/{id:guid}/records", ListRecordsAsync)
            .Produces<DatabaseRecordListView>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status401Unauthorized)
            .Produces(StatusCodes.Status403Forbidden);

        endpoints.MapGet(SubmissionsPath + "/{id:guid}", GetReceiptAsync)
            .RequireAuthorization()
            .Produces<DatabaseSubmissionReceiptView>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status401Unauthorized)
            .Produces(StatusCodes.Status403Forbidden);

        return endpoints;
    }

    internal static async Task<IResult> GetFormAsync(
        Guid id,
        HttpContext httpContext,
        DatabaseSubmissionService submissions,
        CancellationToken cancellationToken)
    {
        if (AccountClaims.GetAccountId(httpContext.User) is null)
        {
            return ApiErrors.Unauthorized();
        }

        var form = await submissions.GetFormAsync(id, cancellationToken);
        return form is null ? ApiErrors.NotFound(ForbiddenReason.AuthorizedForm) : Results.Ok(form);
    }

    /// <summary>
    /// Checks the answers with the submission's rule before the member consents and returns the
    /// entries to show on the consent screen (<c>saved: false</c>). Writes nothing — no record, no
    /// receipt. <c>409 form-version-changed</c> when the form changed since it was loaded.
    /// </summary>
    internal static async Task<IResult> ReviewAsync(
        Guid id,
        ReviewDatabaseSubmissionRequest request,
        HttpContext httpContext,
        DatabaseSubmissionService submissions,
        CancellationToken cancellationToken)
    {
        if (AccountClaims.GetAccountId(httpContext.User) is null)
        {
            return ApiErrors.Unauthorized();
        }

        var outcome = await submissions.ReviewAsync(
            id, request.FormVersionNumber, DatabaseEndpoints.ToAnswerInputs(request.Answers), cancellationToken);
        return outcome switch
        {
            DatabaseSubmissionOutcome.Reviewed reviewed => Results.Ok(new DatabaseTrialPreviewView(
                false,
                reviewed.FormVersionNumber,
                [.. reviewed.Entries.Select(entry => new DatabaseTrialEntryView(entry.Field.Id, entry.Field.Label, entry.Display))])),
            DatabaseSubmissionOutcome.Invalid invalid => ApiErrors.ValidationFailed(invalid.Failures),
            DatabaseSubmissionOutcome.FormChanged => ApiErrors.WithReason(
                StatusCodes.Status409Conflict, DatabaseEndpoints.FormChangedReason, FormChangedMessage),
            _ => ApiErrors.NotFound(ForbiddenReason.AuthorizedForm),
        };
    }

    internal static async Task<IResult> SubmitAsync(
        Guid id,
        SubmitDatabaseEntryRequest request,
        HttpContext httpContext,
        DatabaseSubmissionService submissions,
        CancellationToken cancellationToken)
    {
        if (AccountClaims.GetAccountId(httpContext.User) is not { } callerId)
        {
            return ApiErrors.Unauthorized();
        }

        var outcome = await submissions.SubmitAsync(
            new DatabaseSubmissionCommand(
                id,
                callerId,
                request.SubmissionId,
                request.FormVersionNumber,
                request.Consent,
                DatabaseEndpoints.ToAnswerInputs(request.Answers),
                DatabaseSubmissionSource.FormLink),
            cancellationToken);

        return outcome switch
        {
            DatabaseSubmissionOutcome.Created created =>
                Results.Created($"{SubmissionsPath}/{created.Receipt.Id}", created.Receipt),
            DatabaseSubmissionOutcome.Replayed replayed => Results.Ok(replayed.Receipt),
            DatabaseSubmissionOutcome.Unavailable => ApiErrors.NotFound(ForbiddenReason.AuthorizedForm),
            DatabaseSubmissionOutcome.Invalid invalid => ApiErrors.ValidationFailed(invalid.Failures),
            DatabaseSubmissionOutcome.ConsentMissing => ApiErrors.Refused(
                ConsentRequiredReason,
                DatabaseSubmissionRules.ConsentMissingMessage,
                [new(DatabaseSubmissionRules.ConsentKey, DatabaseSubmissionRules.ConsentRequiredMessage)]),
            DatabaseSubmissionOutcome.FormChanged => ApiErrors.WithReason(
                StatusCodes.Status409Conflict, DatabaseEndpoints.FormChangedReason, FormChangedMessage),
            DatabaseSubmissionOutcome.KeyReused => ApiErrors.WithReason(
                StatusCodes.Status409Conflict, KeyReusedReason, KeyReusedMessage),
            _ => throw new InvalidOperationException($"Unhandled outcome {outcome.GetType().Name}."),
        };
    }

    /// <summary>
    /// The consented records of a database, with content, for a designated data manager holding
    /// <c>read-consented-submissions</c> now (<see cref="DatabaseRecordReaders.CanReadAsync"/>).
    /// Someone who cannot even see the database gets <c>403 database</c> (as for a missing id);
    /// someone who sees it but may not read records (e.g. its owner) gets <c>403 database-records</c>.
    /// #146 builds the submitter's own list, the timeline and withdrawal on top of this.
    /// </summary>
    internal static async Task<IResult> ListRecordsAsync(
        Guid id,
        HttpContext httpContext,
        AppDbContext dbContext,
        RequestAccountPermissions permissions,
        DatabaseSubmissionService submissions,
        CancellationToken cancellationToken)
    {
        if (AccountClaims.GetAccountId(httpContext.User) is not { } viewerId)
        {
            return ApiErrors.Unauthorized();
        }

        if (!await DatabaseRecordReaders.CanReadAsync(dbContext, permissions, viewerId, id, cancellationToken))
        {
            var hasPermission = await DatabaseRecordReaders.HasReadPermissionAsync(permissions, viewerId, cancellationToken);
            var visible = await dbContext.Databases
                .Where(DatabaseAccess.ListedFor(viewerId, hasPermission, dbContext.DatabaseDataManagers))
                .AnyAsync(database => database.Id == id, cancellationToken);
            return ApiErrors.NotFound(visible ? ForbiddenReason.DatabaseRecords : ForbiddenReason.Database);
        }

        return Results.Ok(new DatabaseRecordListView(id, await submissions.ListRecordsAsync(id, cancellationToken)));
    }

    /// <summary>A receipt, for its submitter only; anyone else gets the same <c>403</c> as for a
    /// missing id.</summary>
    internal static async Task<IResult> GetReceiptAsync(
        Guid id,
        HttpContext httpContext,
        DatabaseSubmissionService submissions,
        CancellationToken cancellationToken)
    {
        if (AccountClaims.GetAccountId(httpContext.User) is not { } callerId)
        {
            return ApiErrors.Unauthorized();
        }

        var receipt = await submissions.GetReceiptAsync(id, callerId, cancellationToken);
        return receipt is null ? ApiErrors.NotFound(ForbiddenReason.SubmissionReceipt) : Results.Ok(receipt);
    }
}
